<?php

$this->widget('zii.widgets.CDetailView', array(
    'data' => $model,
    'attributes' => array(
        'id',
        array(
            'label'=>'所属地区',
            'value'=>$model->areaInfo->title,
        ),
        'authorInfo.truename',
        'title_cn',
        'title_en',
        'title_local',
        'address_cn',
        'address_en',
        'address_local',
        'long',
        'lat',
        'mapZoom',
        'score',
        'scorer',
        'cost',
        'coster',
        'traffic',
        'content',
        'url',
        'phone',
        'email',
        'fax',
        'brand',
        'star',
        'openTime',
        'units',
        'sourceurl',
        'sourceinfo',
        'classify',
        'favorite',
        'hits',
        'attach',
        'wanna',
        'visited',
        'status',
        array(
            'label'=>$model->getAttributeLabel('cTime'),
            'value'=>tools::formatTime($model->cTime),
        ),
        array(
            'label'=>$model->getAttributeLabel('updateTime'),
            'value'=>tools::formatTime($model->updateTime),
        ),
    ),
    'itemCssClass' => '',
    'itemTemplate' => '<tr><td style="width:10%" class="text-right"><b>{label}</b></td><td>{value}</td></tr>',
    'htmlOptions' => array('class' => 'table table-hover table-striped')
));
?>
